### ISSUE TITLE
Unable to add the directive to more than one model

### ISSUE THREAD

**Issue by Tedsterh** [multimeric/AmplifyCountDirective#6]
I get this error after adding the directive to more than one model, I am able to push successfully when it is just the one.
`An error occurred during the push operation: There is already a Construct with name '[object Object]CountResolver' in TransformerNestedStack [countResolverStack]`

I am not doing anything other than running `amplify push`

**Comment by multimeric** [comment]
Oh yep, good call. I'll have a look.

**Comment by Tedsterh** [comment]
Amazing thank you for the quick response! 
Fantastic package, currently using opensearch for totals but it seems to be maxing out at 10k documents, this package returns a much more reliable count.

**Comment by Tedsterh** [comment]
I seem to be hitting a weird npm error currently `Error: EACCES: permission denied, rename '/usr/local/lib/node_modules/amplify-count-directive' -> '/usr/local/lib/node_modules/.amplify-count-directive-HAjrWKtK'`

**Comment by Tedsterh** [comment]
I have already done that but sadly got the same error.

<img width="1220" alt="Screenshot 2022-03-15 at 11 52 29" src="https://user-images.githubusercontent.com/56851744/158372404-75dc70a5-43d4-484a-9280-c00b46735c9b.png">

**Comment by multimeric** [comment]
Sorry, I posted the wrong command. You need the `-g` for both installing and uninstalling.

**Comment by Tedsterh** [comment]
Weirdly exactly the same issue 😅

**Comment by multimeric** [comment]
Try `rm`'ing the directory it's trying to copy to.

**Comment by Tedsterh** [comment]
Okay while I figure out the npm issue, I have also found another. 
I cannot call the count from inside a lambda function as an IAM user

**Comment by Tedsterh** [comment]
Also I am getting new errors from npm `git dep preparation failed`

**Comment by multimeric** [comment]
Okay. I've uploaded a beta version to npm. Try to `sudo npm install -g amplify-count-directive@fix-6` or however you initially installed this package. This is pre-compiled so you shouldn't have any dependency issues hopefully.

**Comment by Tedsterh** [comment]
That has installed now and has let me add count to multiple models as well, seems to be working perfectly, thank you for your help!

Any thoughts on why I can't call the count from inside a lambda function, should I open a different issue?

**Comment by multimeric** [comment]
> Any thoughts on why I can't call the count from inside a lambda function, should I open a different issue?

I'm not actually sure what you mean by this. Do you mean you can't hit the `countFoo` graphql endpoint from inside the lambda? Because that would be down to the permissions you have given the function. e.g. https://docs.amplify.aws/cli/function/#function-templates

**Comment by Tedsterh** [comment]
I am able to call list and search on the model inside the lambda but I cannot seem to call the count, I just get a null value

**Comment by multimeric** [comment]
Okay please open another issue and I can try to debug.

**Comment by Tedsterh** [comment]
Will do, sadly the update failed with this error 
`Only one resolver is allowed per field. (Service: AWSAppSync; Status Code: 400; Error Code: BadRequestException; Request ID: 98cb4b77-7377-412d-aeb0-5f5201cfd130; Proxy: null)`

**Comment by Tedsterh** [comment]
With the new naming I think it has tried to create 2 for one model, I will remove it push and add it back to see if it works

**Comment by multimeric** [comment]
I think most likely the old resolver is still there as well. I'm not sure why cloudformation didn't remove it. Try using `aws appsync   
list-resolvers --api-id <value> --type-name <value>` to check.
